[package]
name = "jest"
version = "0.1.0"
edition = "2021"
authors = ["Sable", "ylythechromosome"]
license = "MIT"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
